Sprint 3/step 1
RuslanKerimovN/burger_practicum pull request #6
Opened 2023-10-28 11:04 UTC by RuslanKerimovN

2023-10-28 11:51 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
 - Настроены все редиректы
 - Отличная работа с формами
 - Есть механизм обновления токена

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Модалка с номером заказа не закрывается нажатием на крестик или на подложку
- `/reset-password` не должен быть доступен напрямую, только через `/forgot-password`
- Лого хедера следует сделать ссылкой на главную страницу

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-10-28 11:51 UTC, andryxxa93 commented on src/components/protected-user-element/protected-user-element.tsx
> +        let cookie = getCookie('accessToken');
**Можно лучше**
Так как строки `accessToken ` и `refreshToken ` повторяется в коде часто - их лучше вынести в константы

2023-10-28 11:51 UTC, andryxxa93 commented on src/pages/login-page/login-page.tsx
> +    const [password, setPassword] = useInput('1111111111');
**Можно лучше**
Лучше свои данные не хардкодить

2023-10-28 13:15 UTC, RuslanKerimovN commented
Спасибо за проверку и замечания!

2023-10-29 07:25 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-10-29 07:40 UTC, merged